// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADeyERSI_s-edPLDfPFiBEY32z1rrhC0k',
    appId: '1:1021903291694:web:4602c540526a80bdbb26bf',
    messagingSenderId: '1021903291694',
    projectId: 'friendlychat-acf65',
    authDomain: 'friendlychat-acf65.firebaseapp.com',
    storageBucket: 'friendlychat-acf65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdVmz4yhtAu-JwZ35aIDmMvhJxTIEegu8',
    appId: '1:1021903291694:android:62c0791036252e79bb26bf',
    messagingSenderId: '1021903291694',
    projectId: 'friendlychat-acf65',
    storageBucket: 'friendlychat-acf65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcAl-DgyWuW_AysEII_VuXzCJVXNLM9_Q',
    appId: '1:1021903291694:ios:12d26d27ed6f7c5fbb26bf',
    messagingSenderId: '1021903291694',
    projectId: 'friendlychat-acf65',
    storageBucket: 'friendlychat-acf65.appspot.com',
    iosClientId: '1021903291694-9f6mboh2t0l7k24f381mmp49mk5ok2gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcAl-DgyWuW_AysEII_VuXzCJVXNLM9_Q',
    appId: '1:1021903291694:ios:eead7f717941be77bb26bf',
    messagingSenderId: '1021903291694',
    projectId: 'friendlychat-acf65',
    storageBucket: 'friendlychat-acf65.appspot.com',
    iosClientId: '1021903291694-4m6kirouhdopv2r605c8hkh469hidqtf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject.RunnerTests',
  );
}
